# Generated by Django 4.2.1 on 2023-05-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_groupdivinfo_thing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdivinfo',
            old_name='thing',
            new_name='name',
        ),
    ]
