# Generated by Django 4.2.1 on 2023-05-24 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_alter_groupdivinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdatainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='groupdivinfo',
        ),
    ]
