# Generated by Django 4.2.1 on 2023-05-24 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_userdatainfo_delete_groupdivinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliancesdatainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('usera', models.CharField(max_length=100)),
                ('appliancename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='groupdatainfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('userg', models.CharField(max_length=100)),
                ('groupname', models.CharField(max_length=100)),
            ],
        ),
    ]
