# Generated by Django 4.2.1 on 2023-05-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_appliancesdatainfo_groupdatainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancesdatainfo',
            name='gpname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
