# Generated by Django 4.2.1 on 2023-05-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0010_appliancesdatainfo_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdatainfo',
        ),
    ]
